//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutStatistics
    {
        public long id { get; set; }
        public string name { get; set; }
        public int quantity { get; set; }
        public string icon { get; set; }
        public long aboutId { get; set; }
    
        public virtual About About { get; set; }
    }
}
