//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public About()
        {
            this.AboutItems = new HashSet<AboutItems>();
            this.AboutSponsors = new HashSet<AboutSponsors>();
            this.AboutStatistics = new HashSet<AboutStatistics>();
            this.AboutTecnologies = new HashSet<AboutTecnologies>();
        }
    
        public long id { get; set; }
        public string sectionName { get; set; }
        public string title { get; set; }
        public string mainSubtitle { get; set; }
        public string secondarySubtitle { get; set; }
        public string description { get; set; }
        public string mainImagePath { get; set; }
        public long generalPageId { get; set; }
    
        public virtual GeneralPage GeneralPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AboutItems> AboutItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AboutSponsors> AboutSponsors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AboutStatistics> AboutStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AboutTecnologies> AboutTecnologies { get; set; }
    }
}
