//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeItems
    {
        public long id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string icon { get; set; }
        public string linkUrl { get; set; }
        public bool enabledItem { get; set; }
        public long homeId { get; set; }
    
        public virtual Home Home { get; set; }
    }
}
