//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Home()
        {
            this.HomeItems = new HashSet<HomeItems>();
        }
    
        public long id { get; set; }
        public string sectionName { get; set; }
        public string title { get; set; }
        public string subtitle { get; set; }
        public string backgroundImagePath { get; set; }
        public string startButton { get; set; }
        public string videoButton { get; set; }
        public bool videoButtonUrl { get; set; }
        public long generalPageId { get; set; }
    
        public virtual GeneralPage GeneralPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeItems> HomeItems { get; set; }
    }
}
