//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbConnection : DbContext
    {
        public DbConnection()
            : base("name=DbConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<AboutItems> AboutItems { get; set; }
        public virtual DbSet<AboutSponsors> AboutSponsors { get; set; }
        public virtual DbSet<AboutStatistics> AboutStatistics { get; set; }
        public virtual DbSet<AboutTecnologies> AboutTecnologies { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<ContactData> ContactData { get; set; }
        public virtual DbSet<ContactMessages> ContactMessages { get; set; }
        public virtual DbSet<GeneralPage> GeneralPage { get; set; }
        public virtual DbSet<Home> Home { get; set; }
        public virtual DbSet<HomeItems> HomeItems { get; set; }
        public virtual DbSet<Portfolio> Portfolio { get; set; }
        public virtual DbSet<PortfolioItems> PortfolioItems { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<ServicesEmployees> ServicesEmployees { get; set; }
        public virtual DbSet<ServicesItems> ServicesItems { get; set; }
    }
}
